### PR TITLE
libconfig: fix compilation error with V1.5.0

### PR DESCRIPTION
**Pull request by bgrube**
the signature setting[std::string] was removed; fix code to use
setting[const char*] instead; tested to work with V1.4.9

### CODE REVIEW

**Comment by legordian** [comment]
Merged, thank you!
